title: Dongchen Li's Homepage
page-top-title: Dongchen Li
top-section-bg-text: Computer Science
home-subtitle: Dongcheni&ensp;|&ensp;李东晨
# copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
