title: Dongchen Li's Homepage
page-top-title: Dongchen Li
top-section-bg-text: Ph.D. Candidate at Waseda University
home-subtitle: Dongchen Li&ensp;|&ensp;李 东晨
# copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
